version: '3.8'

services:
  validra-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: validra-engine
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_READ_TIMEOUT=60
      - SERVER_WRITE_TIMEOUT=60
      - DB_TYPE=postgres
      - DB_HOST=localpg.orb.local
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=validra
      - DB_SSL_MODE=disable
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3